dokon@blizzard2:~/dockerfile_oracle> 
dokon@blizzard2:~/dockerfile_oracle> docker build . -t ora122010
Sending build context to Docker daemon  169.3MB
Step 1/17 : FROM opensuse/leap:15.1
 ---> 9a7d78396082
Step 2/17 : ARG GOPATH=/gopath
 ---> Using cache
 ---> afbdb38846b3
Step 3/17 : ARG GOROOT=/goroot
 ---> Using cache
 ---> e06895426a8b
Step 4/17 : ENV GOROOT=${GOROOT}
 ---> Using cache
 ---> 243bedc4c5d0
Step 5/17 : ENV GOPATH=${GOPATH}
 ---> Using cache
 ---> b5c1837ba198
Step 6/17 : ENV PATH=${GOROOT}/bin:${GOPATH}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ---> Using cache
 ---> 4c8e1f62d8e6
Step 7/17 : RUN zypper --non-interactive update &&       zypper --non-interactive install --no-recommends --force-resolution      tar      gzip      unzip      python3      python3-pip      python3-devel      gcc=7      gcc-c++=7      libgthread-2_0-0=2.54.3      libaio
 ---> Running in a93347ccc7c4
Building repository 'Non-OSS Repository' cache [....done]
Building repository 'Main Repository' cache [....done]
Building repository 'Main Update Repository' cache [....done]
Building repository 'Update Repository (Non-Oss)' cache [....done]
Loading repository data...
Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
Warning: Repository 'Update Repository (Non-Oss)' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...

The following 3 packages are going to be upgraded:
  libkeyutils1 libsystemd0 libudev1

3 packages to upgrade.
Overall download size: 620.1 KiB. Already cached: 0 B. No additional space will be used or freed after the operation.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libkeyutils1-1.5.10-lp151.5.3.1.x86_64 (1/3),  23.6 KiB ( 40.1 KiB unpacked)
Retrieving: libkeyutils1-1.5.10-lp151.5.3.1.x86_64.rpm [..done]
Retrieving package libsystemd0-234-lp151.26.34.1.x86_64 (2/3), 381.2 KiB (596.1 KiB unpacked)
Retrieving: libsystemd0-234-lp151.26.34.1.x86_64.rpm [done]
Retrieving package libudev1-234-lp151.26.34.1.x86_64 (3/3), 215.3 KiB (142.2 KiB unpacked)
Retrieving: libudev1-234-lp151.26.34.1.x86_64.rpm [.done (9.5 KiB/s)]

Checking for file conflicts: [....done]
(1/3) Installing: libkeyutils1-1.5.10-lp151.5.3.1.x86_64 [..........done]
(2/3) Installing: libsystemd0-234-lp151.26.34.1.x86_64 [..........done]
(3/3) Installing: libudev1-234-lp151.26.34.1.x86_64 [.........done]
 
Loading repository data...
Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
Warning: Repository 'Update Repository (Non-Oss)' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...
'libaio' not found in package names. Trying capabilities.
Resolving package dependencies...

The following 43 NEW packages are going to be installed:
  binutils cpp cpp7 gcc gcc-c++ gcc7 gcc7-c++ glibc-devel gzip libaio1 libasan4 libatomic1 libcilkrts5 libctf-nobfd0 libctf0 libexpat1 libgomp1 libgthread-2_0-0 libisl15 libitm1 liblsan0 libmpc3 libmpfr6 libmpx2 libmpxwrappers2 libpython3_6m1_0 libstdc++6-devel-gcc7 libtsan0 libubsan0 linux-glibc-devel pkg-config python-rpm-macros python3 python3-appdirs python3-base python3-devel python3-packaging python3-pip python3-pyparsing python3-setuptools python3-six tar unzip

43 new packages to install.
Overall download size: 65.2 MiB. Already cached: 0 B. After the operation, additional 265.2 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libaio1-0.3.109-lp151.2.2.x86_64 (1/43),  20.2 KiB ( 31.5 KiB unpacked)
Retrieving: libaio1-0.3.109-lp151.2.2.x86_64.rpm [.done (2.4 KiB/s)]
Retrieving package libisl15-0.18-lp151.2.70.x86_64 (2/43), 546.4 KiB (  1.7 MiB unpacked)
Retrieving: libisl15-0.18-lp151.2.70.x86_64.rpm [done]
Retrieving package libmpfr6-4.0.1-lp151.2.70.x86_64 (3/43), 214.3 KiB (500.6 KiB unpacked)
Retrieving: libmpfr6-4.0.1-lp151.2.70.x86_64.rpm [.done (5.2 KiB/s)]
Retrieving package libmpx2-8.2.1+r264010-lp151.1.33.x86_64 (4/43),  19.1 KiB ( 18.3 KiB unpacked)
Retrieving: libmpx2-8.2.1+r264010-lp151.1.33.x86_64.rpm [done]
Retrieving package libmpxwrappers2-8.2.1+r264010-lp151.1.33.x86_64 (5/43),  17.8 KiB ( 14.2 KiB unpacked)
Retrieving: libmpxwrappers2-8.2.1+r264010-lp151.1.33.x86_64.rpm [done]
Retrieving package linux-glibc-devel-4.15-lp151.2.72.noarch (6/43),   1.3 MiB (  5.7 MiB unpacked)
Retrieving: linux-glibc-devel-4.15-lp151.2.72.noarch.rpm [.done (10.9 KiB/s)]
Retrieving package pkg-config-0.29.2-lp151.2.70.x86_64 (7/43), 230.1 KiB (675.4 KiB unpacked)
Retrieving: pkg-config-0.29.2-lp151.2.70.x86_64.rpm [done]
Retrieving package tar-1.30-lp151.2.1.x86_64 (8/43), 209.1 KiB (470.6 KiB unpacked)
Retrieving: tar-1.30-lp151.2.1.x86_64.rpm [.done (2.4 KiB/s)]
Retrieving package unzip-6.00-lp151.5.1.x86_64 (9/43), 107.0 KiB (262.8 KiB unpacked)
Retrieving: unzip-6.00-lp151.5.1.x86_64.rpm [done]
Retrieving package libmpc3-1.1.0-lp151.2.70.x86_64 (10/43),  48.3 KiB ( 99.5 KiB unpacked)
Retrieving: libmpc3-1.1.0-lp151.2.70.x86_64.rpm [.done (12.3 KiB/s)]
Retrieving package gzip-1.10-lp151.4.3.1.x86_64 (11/43), 140.0 KiB (313.5 KiB unpacked)
Retrieving: gzip-1.10-lp151.4.3.1.x86_64.rpm [.done (14.6 KiB/s)]
Retrieving package libasan4-7.5.0+r278197-lp151.2.18.1.x86_64 (12/43), 360.9 KiB (  1.3 MiB unpacked)
Retrieving: libasan4-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [done]
Retrieving package libatomic1-10.2.1+git583-lp151.2.2.x86_64 (13/43),  22.7 KiB ( 26.1 KiB unpacked)
Retrieving: libatomic1-10.2.1+git583-lp151.2.2.x86_64.rpm [.done (5.2 KiB/s)]
Retrieving package libcilkrts5-7.5.0+r278197-lp151.2.18.1.x86_64 (14/43),  64.2 KiB (120.1 KiB unpacked)
Retrieving: libcilkrts5-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [done]
Retrieving package libctf-nobfd0-2.35.1-lp151.3.12.1.x86_64 (15/43),  91.1 KiB (107.0 KiB unpacked)
Retrieving: libctf-nobfd0-2.35.1-lp151.3.12.1.x86_64.rpm [done]
Retrieving package libexpat1-2.2.5-lp151.3.6.1.x86_64 (16/43),  75.0 KiB (198.3 KiB unpacked)
Retrieving: libexpat1-2.2.5-lp151.3.6.1.x86_64.rpm [.done (6.6 KiB/s)]
Retrieving package libgomp1-10.2.1+git583-lp151.2.2.x86_64 (17/43), 143.9 KiB (352.3 KiB unpacked)
Retrieving: libgomp1-10.2.1+git583-lp151.2.2.x86_64.rpm [done]
Retrieving package libgthread-2_0-0-2.54.3-lp151.7.3.1.x86_64 (18/43),  47.4 KiB (  6.0 KiB unpacked)
Retrieving: libgthread-2_0-0-2.54.3-lp151.7.3.1.x86_64.rpm [done]
Retrieving package libitm1-10.2.1+git583-lp151.2.2.x86_64 (19/43),  39.1 KiB ( 94.4 KiB unpacked)
Retrieving: libitm1-10.2.1+git583-lp151.2.2.x86_64.rpm [.done (959 B/s)]
Retrieving package liblsan0-10.2.1+git583-lp151.2.2.x86_64 (20/43), 152.7 KiB (361.2 KiB unpacked)
Retrieving: liblsan0-10.2.1+git583-lp151.2.2.x86_64.rpm [done]
Retrieving package libtsan0-10.2.1+git583-lp151.2.2.x86_64 (21/43), 317.4 KiB (  1.1 MiB unpacked)
Retrieving: libtsan0-10.2.1+git583-lp151.2.2.x86_64.rpm [done]
Retrieving package libubsan0-7.5.0+r278197-lp151.2.18.1.x86_64 (22/43), 137.5 KiB (305.3 KiB unpacked)
Retrieving: libubsan0-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [.done (8.1 KiB/s)]
Retrieving package python-rpm-macros-20200207.5feb6c1-lp151.2.6.1.noarch (23/43),  27.9 KiB ( 50.6 KiB unpacked)
Retrieving: python-rpm-macros-20200207.5feb6c1-lp151.2.6.1.noarch.rpm [done]
Retrieving package glibc-devel-2.26-lp151.19.19.1.x86_64 (24/43), 755.6 KiB (  2.9 MiB unpacked)
Retrieving: glibc-devel-2.26-lp151.19.19.1.x86_64.rpm [.done (3.4 MiB/s)]
Retrieving package cpp7-7.5.0+r278197-lp151.2.18.1.x86_64 (25/43),   7.9 MiB ( 22.0 MiB unpacked)
Retrieving: cpp7-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [.done (4.4 MiB/s)]
Retrieving package libctf0-2.35.1-lp151.3.12.1.x86_64 (26/43),  92.6 KiB (111.2 KiB unpacked)
Retrieving: libctf0-2.35.1-lp151.3.12.1.x86_64.rpm [done]
Retrieving package python3-base-3.6.12-lp151.6.36.1.x86_64 (27/43),   7.6 MiB ( 30.6 MiB unpacked)
Retrieving: python3-base-3.6.12-lp151.6.36.1.x86_64.rpm [..done (5.7 MiB/s)]
Retrieving package libstdc++6-devel-gcc7-7.5.0+r278197-lp151.2.18.1.x86_64 (28/43),   6.7 MiB ( 35.8 MiB unpacked)
Retrieving: libstdc++6-devel-gcc7-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [..done (4.7 MiB/s)]
Retrieving package binutils-2.35.1-lp151.3.12.1.x86_64 (29/43),   5.9 MiB ( 46.5 MiB unpacked)
Retrieving: binutils-2.35.1-lp151.3.12.1.x86_64.rpm [..done (4.8 MiB/s)]
Retrieving package libpython3_6m1_0-3.6.12-lp151.6.36.1.x86_64 (30/43), 859.1 KiB (  2.7 MiB unpacked)
Retrieving: libpython3_6m1_0-3.6.12-lp151.6.36.1.x86_64.rpm [.done (8.1 KiB/s)]
Retrieving package gcc7-7.5.0+r278197-lp151.2.18.1.x86_64 (31/43),  19.7 MiB ( 72.7 MiB unpacked)
Retrieving: gcc7-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [......done (3.7 MiB/s)]
Retrieving package python3-six-1.11.0-lp151.4.3.1.noarch (32/43),  32.2 KiB ( 91.0 KiB unpacked)
Retrieving: python3-six-1.11.0-lp151.4.3.1.noarch.rpm [.done (15.9 KiB/s)]
Retrieving package gcc7-c++-7.5.0+r278197-lp151.2.18.1.x86_64 (33/43),   8.9 MiB ( 23.9 MiB unpacked)
Retrieving: gcc7-c++-7.5.0+r278197-lp151.2.18.1.x86_64.rpm [..done (4.0 MiB/s)]
Retrieving package cpp-7-lp151.3.5.x86_64 (34/43),   9.1 KiB (   82   B unpacked)
Retrieving: cpp-7-lp151.3.5.x86_64.rpm [.done]
Retrieving package python3-pyparsing-2.2.0-lp151.2.1.noarch (35/43), 158.8 KiB (723.3 KiB unpacked)
Retrieving: python3-pyparsing-2.2.0-lp151.2.1.noarch.rpm [.done (5.2 KiB/s)]
Retrieving package python3-appdirs-1.4.3-lp151.2.1.noarch (36/43),  22.5 KiB ( 83.5 KiB unpacked)
Retrieving: python3-appdirs-1.4.3-lp151.2.1.noarch.rpm [done]
Retrieving package gcc-7-lp151.3.5.x86_64 (37/43),  10.1 KiB (    0   B unpacked)
Retrieving: gcc-7-lp151.3.5.x86_64.rpm [done]
Retrieving package python3-packaging-16.8-lp151.2.1.noarch (38/43),  41.8 KiB (161.9 KiB unpacked)
Retrieving: python3-packaging-16.8-lp151.2.1.noarch.rpm [.done (12.1 KiB/s)]
Retrieving package gcc-c++-7-lp151.3.5.x86_64 (39/43),   8.9 KiB (    0   B unpacked)
Retrieving: gcc-c++-7-lp151.3.5.x86_64.rpm [done]
Retrieving package python3-3.6.12-lp151.6.36.1.x86_64 (40/43),  76.4 KiB (141.3 KiB unpacked)
Retrieving: python3-3.6.12-lp151.6.36.1.x86_64.rpm [.done (15.1 KiB/s)]
Retrieving package python3-setuptools-40.5.0-lp151.2.3.1.noarch (41/43), 616.6 KiB (  3.3 MiB unpacked)
Retrieving: python3-setuptools-40.5.0-lp151.2.3.1.noarch.rpm [done]
Retrieving package python3-devel-3.6.12-lp151.6.36.1.x86_64 (42/43), 224.1 KiB (789.2 KiB unpacked)
Retrieving: python3-devel-3.6.12-lp151.6.36.1.x86_64.rpm [.done (369.2 KiB/s)]
Retrieving package python3-pip-10.0.1-lp151.3.6.1.noarch (43/43),   1.6 MiB (  9.0 MiB unpacked)
Retrieving: python3-pip-10.0.1-lp151.3.6.1.noarch.rpm [done]

Checking for file conflicts: [.........done]
( 1/43) Installing: libaio1-0.3.109-lp151.2.2.x86_64 [.....done]
( 2/43) Installing: libisl15-0.18-lp151.2.70.x86_64 [............done]
( 3/43) Installing: libmpfr6-4.0.1-lp151.2.70.x86_64 [...........done]
( 4/43) Installing: libmpx2-8.2.1+r264010-lp151.1.33.x86_64 [....done]
( 5/43) Installing: libmpxwrappers2-8.2.1+r264010-lp151.1.33.x86_64 [.....done]
( 6/43) Installing: linux-glibc-devel-4.15-lp151.2.72.noarch [............done]
( 7/43) Installing: pkg-config-0.29.2-lp151.2.70.x86_64 [...........done]
( 8/43) Installing: tar-1.30-lp151.2.1.x86_64 [...........done]
( 9/43) Installing: unzip-6.00-lp151.5.1.x86_64 [...........done]
Additional rpm output:
update-alternatives: using /usr/bin/unzip-plain to provide /usr/bin/unzip (unzip) in auto mode
update-alternatives: using /usr/bin/funzip-plain to provide /usr/bin/funzip (funzip) in auto mode
update-alternatives: using /usr/bin/unzipsfx-plain to provide /usr/bin/unzipsfx (unzipsfx) in auto mode
update-alternatives: using /usr/bin/zipgrep-plain to provide /usr/bin/zipgrep (zipgrep) in auto mode


(10/43) Installing: libmpc3-1.1.0-lp151.2.70.x86_64 [......done]
(11/43) Installing: gzip-1.10-lp151.4.3.1.x86_64 [..........done]
(12/43) Installing: libasan4-7.5.0+r278197-lp151.2.18.1.x86_64 [............done]
(13/43) Installing: libatomic1-10.2.1+git583-lp151.2.2.x86_64 [....done]
(14/43) Installing: libcilkrts5-7.5.0+r278197-lp151.2.18.1.x86_64 [.......done]
(15/43) Installing: libctf-nobfd0-2.35.1-lp151.3.12.1.x86_64 [......done]
(16/43) Installing: libexpat1-2.2.5-lp151.3.6.1.x86_64 [.........done]
(17/43) Installing: libgomp1-10.2.1+git583-lp151.2.2.x86_64 [.........done]
(18/43) Installing: libgthread-2_0-0-2.54.3-lp151.7.3.1.x86_64 [.....done]
(19/43) Installing: libitm1-10.2.1+git583-lp151.2.2.x86_64 [......done]
(20/43) Installing: liblsan0-10.2.1+git583-lp151.2.2.x86_64 [.........done]
(21/43) Installing: libtsan0-10.2.1+git583-lp151.2.2.x86_64 [............done]
(22/43) Installing: libubsan0-7.5.0+r278197-lp151.2.18.1.x86_64 [.........done]
(23/43) Installing: python-rpm-macros-20200207.5feb6c1-lp151.2.6.1.noarch [.....done]
(24/43) Installing: glibc-devel-2.26-lp151.19.19.1.x86_64 [............done]
(25/43) Installing: cpp7-7.5.0+r278197-lp151.2.18.1.x86_64 [............done]
(26/43) Installing: libctf0-2.35.1-lp151.3.12.1.x86_64 [.......done]
(27/43) Installing: python3-base-3.6.12-lp151.6.36.1.x86_64 [............done]
(28/43) Installing: libstdc++6-devel-gcc7-7.5.0+r278197-lp151.2.18.1.x86_64 [............done]
(29/43) Installing: binutils-2.35.1-lp151.3.12.1.x86_64 [............done]
Additional rpm output:
update-alternatives: using /usr/bin/ld.bfd to provide /usr/bin/ld (ld) in auto mode


(30/43) Installing: libpython3_6m1_0-3.6.12-lp151.6.36.1.x86_64 [............done]
(31/43) Installing: gcc7-7.5.0+r278197-lp151.2.18.1.x86_64 [............done]
(32/43) Installing: python3-six-1.11.0-lp151.4.3.1.noarch [.......done]
(33/43) Installing: gcc7-c++-7.5.0+r278197-lp151.2.18.1.x86_64 [............done]
(34/43) Installing: cpp-7-lp151.3.5.x86_64 [......done]
(35/43) Installing: python3-pyparsing-2.2.0-lp151.2.1.noarch [...........done]
(36/43) Installing: python3-appdirs-1.4.3-lp151.2.1.noarch [.......done]
(37/43) Installing: gcc-7-lp151.3.5.x86_64 [...........done]
(38/43) Installing: python3-packaging-16.8-lp151.2.1.noarch [.........done]
(39/43) Installing: gcc-c++-7-lp151.3.5.x86_64 [.......done]
(40/43) Installing: python3-3.6.12-lp151.6.36.1.x86_64 [........done]
(41/43) Installing: python3-setuptools-40.5.0-lp151.2.3.1.noarch [............done]
Additional rpm output:
update-alternatives: using /usr/bin/easy_install-3.6 to provide /usr/bin/easy_install (easy_install) in auto mode


(42/43) Installing: python3-devel-3.6.12-lp151.6.36.1.x86_64 [............done]
(43/43) Installing: python3-pip-10.0.1-lp151.3.6.1.noarch [............done]
Additional rpm output:
update-alternatives: using /usr/bin/pip3.6 to provide /usr/bin/pip (pip) in auto mode


Removing intermediate container a93347ccc7c4
 ---> 665b8751b7d7
Step 8/17 : COPY ora122010.zip /tmp/ora122010.zip
 ---> 2cb5c2b83f7a
Step 9/17 : RUN mkdir -p ${GOROOT} &&      unzip /tmp/ora122010.zip -d ${GOROOT}
 ---> Running in 3c3ab227fabe
Archive:  /tmp/ora122010.zip
  inflating: /goroot/instantclient_12_2/adrci  
  inflating: /goroot/instantclient_12_2/BASIC_LITE_README  
  inflating: /goroot/instantclient_12_2/genezi  
  inflating: /goroot/instantclient_12_2/libclntshcore.so.12.1  
  inflating: /goroot/instantclient_12_2/libclntsh.so.12.1  
  inflating: /goroot/instantclient_12_2/libipc1.so  
  inflating: /goroot/instantclient_12_2/libmql1.so  
  inflating: /goroot/instantclient_12_2/libnnz12.so  
  inflating: /goroot/instantclient_12_2/libocci.so.12.1  
  inflating: /goroot/instantclient_12_2/libociicus.so  
  inflating: /goroot/instantclient_12_2/libocijdbc12.so  
  inflating: /goroot/instantclient_12_2/libons.so  
  inflating: /goroot/instantclient_12_2/liboramysql12.so  
  inflating: /goroot/instantclient_12_2/ojdbc8.jar  
  inflating: /goroot/instantclient_12_2/uidrvci  
  inflating: /goroot/instantclient_12_2/xstreams.jar  
Removing intermediate container 3c3ab227fabe
 ---> b81c6017f08b
Step 10/17 : ARG ORACLIENT=/goroot/instantclient_12_2
 ---> Running in 2e0f40b38157
Removing intermediate container 2e0f40b38157
 ---> 5e897044e5c1
Step 11/17 : ENV LD_LIBRARY_PATH=${ORACLIENT}/lib:${LD_LIBRARY_PATH}
 ---> Running in 4631fd01a315
Removing intermediate container 4631fd01a315
 ---> 28bd8f5b4eb1
Step 12/17 : RUN python3 -m pip --no-cache install tornado==5.0.2 &&      python3 -m pip --no-cache install pandas &&      python3 -m pip --no-cache install cython
 ---> Running in 51dfadfa1bab
Collecting tornado==5.0.2
  Downloading https://files.pythonhosted.org/packages/cf/d1/3be271ae5eba9fb59df63c9891fdc7d8044b999e8ac145994cdbfd2ae66a/tornado-5.0.2.tar.gz (506kB)
Installing collected packages: tornado
  Running setup.py install for tornado: started
    Running setup.py install for tornado: finished with status 'done'
Successfully installed tornado-5.0.2
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/c3/e2/00cacecafbab071c787019f00ad84ca3185952f6bb9bca9550ed83870d4d/pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5MB)
Collecting python-dateutil>=2.7.3 (from pandas)
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
Collecting pytz>=2017.2 (from pandas)
  Downloading https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl (503kB)
Collecting numpy>=1.15.4 (from pandas)
  Downloading https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas) (1.11.0)
Installing collected packages: python-dateutil, pytz, numpy, pandas
Successfully installed numpy-1.19.5 pandas-1.1.5 python-dateutil-2.8.2 pytz-2021.3
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting cython
  Downloading https://files.pythonhosted.org/packages/d7/04/5890b30102782a3ec9970df3c10f024298803d89624ee23cf75d09bd2548/Cython-0.29.24-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
Installing collected packages: cython
Successfully installed cython-0.29.24
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 51dfadfa1bab
 ---> 0cf2c8ff9e36
Step 13/17 : RUN python3 -m pip --no-cache install cx_Oracle
 ---> Running in 0358d75a20cd
Collecting cx_Oracle
  Downloading https://files.pythonhosted.org/packages/77/c0/72e79c45947ec1c41d89507f546a22658c2603edcfe2c445738725ca2bbb/cx_Oracle-8.2.1-cp36-cp36m-manylinux1_x86_64.whl (818kB)
Installing collected packages: cx-Oracle
Successfully installed cx-Oracle-8.2.1
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 0358d75a20cd
 ---> 8dcfce9116e1
Step 14/17 : RUN groupadd -g 1972 vflow && useradd -g 1972 -u 1972 -m vflow
 ---> Running in aeb23747616e
Group 'mail' not found. Creating the user mailbox file with 0600 mode.
Removing intermediate container aeb23747616e
 ---> 1ac5203c1b38
Step 15/17 : USER 1972:1972
 ---> Running in 80276720cd16
Removing intermediate container 80276720cd16
 ---> ccc3c97a3402
Step 16/17 : WORKDIR /home/vflow
 ---> Running in 3779178b2a16
Removing intermediate container 3779178b2a16
 ---> 640b81df64a6
Step 17/17 : ENV HOME=/home/vflow
 ---> Running in 29171c3e4e53
Removing intermediate container 29171c3e4e53
 ---> a0990d9d5ae2
Successfully built a0990d9d5ae2
Successfully tagged ora122010:latest
dokon@blizzard2:~/dockerfile_oracle>
